### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by Oliver-222** [Oliver-222/Software-Engineering-Project#38]
Look at Build with Gradle Wrapper for more information.

Errors in: 
 location: class WriteRequest
 location: class DataWriteResponse

**Comment by loganullmeyer** [comment]
Added a new constructor for WriteRequest that doesn't require a List of data, since I think there are places that call it without having the data

**Comment by Oliver-222** [comment]
> Added a new constructor for WriteRequest that doesn't require a List of data, since I think there are places that call it without having the data

Looks good, only issues now are in:

location: class DataWriteResponse

**Comment by Oliver-222** [comment]
fixed compiling issues and have a current PR up for it. Tests have been altered and may need to be adjusted, but everything complies.
